/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */

#include <ngx_protobuf.h>
#include <ngx_adx_com_proto.h>

/* ComRequest.AdxSlot.Banner field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_banner_width = {
    ngx_string("width"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_banner_height = {
    ngx_string("height"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.AdxSlot.Native field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_native_icon_width = {
    ngx_string("icon_width"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_native_icon_height = {
    ngx_string("icon_height"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_native_width = {
    ngx_string("width"),
    3,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_native_height = {
    ngx_string("height"),
    4,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.AdxSlot.Video field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_video_width = {
    ngx_string("width"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_video_height = {
    ngx_string("height"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_video_min_duration = {
    ngx_string("min_duration"),
    3,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_video_max_duration = {
    ngx_string("max_duration"),
    4,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.AdxSlot field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_adx_slot_id = {
    ngx_string("adx_slot_id"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_adx_slot_sequence_id = {
    ngx_string("adx_slot_sequence_id"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_adx_slot_type = {
    ngx_string("adx_slot_type"),
    3,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_adx_slot_adx_slot_type_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_banner = {
    ngx_string("banner"),
    4,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_adx_slot_banner_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_adx_slot_banner__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_adx_slot_banner__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_adx_slot_banner__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_native = {
    ngx_string("native"),
    5,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_adx_slot_native_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_adx_slot_native__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_adx_slot_native__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_adx_slot_native__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_video = {
    ngx_string("video"),
    6,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_adx_slot_video_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_adx_slot_video__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_adx_slot_video__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_adx_slot_video__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot_price_floor = {
    ngx_string("price_floor"),
    7,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.Device.DeviceID field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_device_device_id_id = {
    ngx_string("id"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_device_id_type = {
    ngx_string("type"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_device_device_id_type_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.Device field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_device_device_id = {
    ngx_string("device_id"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_REPEATED,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_device_device_id_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_device_device_id__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_device_device_id__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_device_device_id__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_device_type = {
    ngx_string("device_type"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_device_device_type_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_os = {
    ngx_string("os"),
    3,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_device_os_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_os_version = {
    ngx_string("os_version"),
    4,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_carrier = {
    ngx_string("carrier"),
    5,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_device_carrier_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_connection = {
    ngx_string("connection"),
    6,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_request_device_connection_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_brand = {
    ngx_string("brand"),
    7,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_model = {
    ngx_string("model"),
    8,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_user_agent = {
    ngx_string("user_agent"),
    9,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device_ip = {
    ngx_string("ip"),
    10,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest.App field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_app_app_id = {
    ngx_string("app_id"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_app_app_category = {
    ngx_string("app_category"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComRequest field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_request_adx = {
    ngx_string("adx"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_bid = {
    ngx_string("bid"),
    2,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_request_adx_slot = {
    ngx_string("adx_slot"),
    3,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_REPEATED,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_adx_slot_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_adx_slot__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_adx_slot__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_adx_slot__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_device = {
    ngx_string("device"),
    4,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_device_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_device__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_device__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_device__size
};

ngx_protobuf_field_descriptor_t
ngx_com_request_app = {
    ngx_string("app"),
    5,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_request_app_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_request_app__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_request_app__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_request_app__size
};

/* ComResponse.AdxSlot field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_adx_slot_id = {
    ngx_string("adx_slot_id"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_adx_slot_sequence_id = {
    ngx_string("adx_slot_sequence_id"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_adx_slot_type = {
    ngx_string("adx_slot_type"),
    3,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_ENUM,
    sizeof(ngx_com_response_adx_slot_adx_slot_type_e),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_price = {
    ngx_string("price"),
    4,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_INT32,
    sizeof(int32_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_template = {
    ngx_string("template"),
    5,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot_ext = {
    ngx_string("ext"),
    6,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

/* ComResponse field descriptors */

ngx_protobuf_field_descriptor_t
ngx_com_response_bid = {
    ngx_string("bid"),
    1,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_OPTIONAL,
    NGX_PROTOBUF_TYPE_STRING,
    sizeof(ngx_str_t),
    0,
    (ngx_protobuf_pack_pt)
        NULL,
    (ngx_protobuf_unpack_pt)
        NULL,
    (ngx_protobuf_size_pt)
        NULL
};

ngx_protobuf_field_descriptor_t
ngx_com_response_adx_slot = {
    ngx_string("adx_slot"),
    2,
    NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED,
    NGX_PROTOBUF_LABEL_REPEATED,
    NGX_PROTOBUF_TYPE_MESSAGE,
    sizeof(ngx_com_response_adx_slot_t),
    0,
    (ngx_protobuf_pack_pt)
        ngx_com_response_adx_slot__pack,
    (ngx_protobuf_unpack_pt)
        ngx_com_response_adx_slot__unpack,
    (ngx_protobuf_size_pt)
        ngx_com_response_adx_slot__size
};

static ngx_protobuf_module_t
ngx_adx_com_proto_module_ctx = {
    NULL
};

ngx_module_t ngx_adx_com_proto_module = {
    NGX_MODULE_V1,
    &ngx_adx_com_proto_module_ctx,
    NULL,
    NGX_PROTOBUF_MODULE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NGX_MODULE_V1_PADDING
};

/* ComRequest.AdxSlot.Banner message methods */

    ngx_int_t
ngx_com_request_adx_slot_banner__is_initialized(
        ngx_com_request_adx_slot_banner_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_request_adx_slot_banner__unpack(
        ngx_com_request_adx_slot_banner_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.AdxSlot.Banner.width */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->width) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_width = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.AdxSlot.Banner.height */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->height) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_height = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_adx_slot_banner__size(
        ngx_com_request_adx_slot_banner_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_width) {
        size += ngx_protobuf_size_uint32_field(obj->width, 1);
    }
    if (obj->__has_height) {
        size += ngx_protobuf_size_uint32_field(obj->height, 2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_adx_slot_banner__pack(
        ngx_com_request_adx_slot_banner_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_adx_slot_banner__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_width) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->width,
                1);
    }
    if (obj->__has_height) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->height,
                2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.AdxSlot.Native message methods */

    ngx_int_t
ngx_com_request_adx_slot_native__is_initialized(
        ngx_com_request_adx_slot_native_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_request_adx_slot_native__unpack(
        ngx_com_request_adx_slot_native_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.AdxSlot.Native.icon_width */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->icon_width) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_icon_width = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.AdxSlot.Native.icon_height */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->icon_height) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_icon_height = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComRequest.AdxSlot.Native.width */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->width) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_width = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComRequest.AdxSlot.Native.height */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->height) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_height = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_adx_slot_native__size(
        ngx_com_request_adx_slot_native_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_icon_width) {
        size += ngx_protobuf_size_uint32_field(obj->icon_width, 1);
    }
    if (obj->__has_icon_height) {
        size += ngx_protobuf_size_uint32_field(obj->icon_height, 2);
    }
    if (obj->__has_width) {
        size += ngx_protobuf_size_uint32_field(obj->width, 3);
    }
    if (obj->__has_height) {
        size += ngx_protobuf_size_uint32_field(obj->height, 4);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_adx_slot_native__pack(
        ngx_com_request_adx_slot_native_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_adx_slot_native__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_icon_width) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->icon_width,
                1);
    }
    if (obj->__has_icon_height) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->icon_height,
                2);
    }
    if (obj->__has_width) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->width,
                3);
    }
    if (obj->__has_height) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->height,
                4);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.AdxSlot.Video message methods */

    ngx_int_t
ngx_com_request_adx_slot_video__is_initialized(
        ngx_com_request_adx_slot_video_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_request_adx_slot_video__unpack(
        ngx_com_request_adx_slot_video_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.AdxSlot.Video.width */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->width) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_width = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.AdxSlot.Video.height */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->height) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_height = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComRequest.AdxSlot.Video.min_duration */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->min_duration) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_min_duration = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComRequest.AdxSlot.Video.max_duration */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->max_duration) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_max_duration = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_adx_slot_video__size(
        ngx_com_request_adx_slot_video_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_width) {
        size += ngx_protobuf_size_uint32_field(obj->width, 1);
    }
    if (obj->__has_height) {
        size += ngx_protobuf_size_uint32_field(obj->height, 2);
    }
    if (obj->__has_min_duration) {
        size += ngx_protobuf_size_uint32_field(obj->min_duration, 3);
    }
    if (obj->__has_max_duration) {
        size += ngx_protobuf_size_uint32_field(obj->max_duration, 4);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_adx_slot_video__pack(
        ngx_com_request_adx_slot_video_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_adx_slot_video__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_width) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->width,
                1);
    }
    if (obj->__has_height) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->height,
                2);
    }
    if (obj->__has_min_duration) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->min_duration,
                3);
    }
    if (obj->__has_max_duration) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->max_duration,
                4);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.AdxSlot message methods */

    ngx_int_t
ngx_com_request_adx_slot__is_initialized(
        ngx_com_request_adx_slot_t *obj)
{
    return 1; /* no required fields */
}

    static ngx_int_t
ngx_com_request_adx_slot__unpack_banner(
        ngx_com_request_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    u_char     *end0;
    u_char     *end;
    ngx_int_t   rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->banner != NULL) {
        ngx_com_request_adx_slot_banner__clear(obj->banner);
    } else {
        if (ctx->pool != NULL) {
            obj->banner = ngx_com_request_adx_slot_banner__alloc(ctx->pool);
        }
        if (obj->banner == NULL) {
            return NGX_ERROR;
        }
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_adx_slot_banner__unpack(obj->banner, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_banner = 1;
    }

    return rc;
}

    static ngx_int_t
ngx_com_request_adx_slot__unpack_native(
        ngx_com_request_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    u_char     *end0;
    u_char     *end;
    ngx_int_t   rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->native != NULL) {
        ngx_com_request_adx_slot_native__clear(obj->native);
    } else {
        if (ctx->pool != NULL) {
            obj->native = ngx_com_request_adx_slot_native__alloc(ctx->pool);
        }
        if (obj->native == NULL) {
            return NGX_ERROR;
        }
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_adx_slot_native__unpack(obj->native, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_native = 1;
    }

    return rc;
}

    static ngx_int_t
ngx_com_request_adx_slot__unpack_video(
        ngx_com_request_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    u_char     *end0;
    u_char     *end;
    ngx_int_t   rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->video != NULL) {
        ngx_com_request_adx_slot_video__clear(obj->video);
    } else {
        if (ctx->pool != NULL) {
            obj->video = ngx_com_request_adx_slot_video__alloc(ctx->pool);
        }
        if (obj->video == NULL) {
            return NGX_ERROR;
        }
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_adx_slot_video__unpack(obj->video, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_video = 1;
    }

    return rc;
}

    ngx_int_t
ngx_com_request_adx_slot__unpack(
        ngx_com_request_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    uint32_t      mlen;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.AdxSlot.adx_slot_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->adx_slot_id,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.AdxSlot.adx_slot_sequence_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->adx_slot_sequence_id) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_sequence_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComRequest.AdxSlot.adx_slot_type */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->adx_slot_type) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_type = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComRequest.AdxSlot.banner */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request_adx_slot__unpack_banner(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 5: /* ComRequest.AdxSlot.native */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request_adx_slot__unpack_native(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 6: /* ComRequest.AdxSlot.video */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request_adx_slot__unpack_video(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 7: /* ComRequest.AdxSlot.price_floor */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->price_floor) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_price_floor = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_adx_slot__size(
        ngx_com_request_adx_slot_t *obj)
{
    size_t      size = 0;
    size_t      n;
    ngx_uint_t  i;

    if (obj->__has_adx_slot_id) {
        size += ngx_protobuf_size_string_field(&obj->adx_slot_id, 1);
    }
    if (obj->__has_adx_slot_sequence_id) {
        size += ngx_protobuf_size_uint32_field(obj->adx_slot_sequence_id, 2);
    }
    if (obj->__has_adx_slot_type) {
        size += ngx_protobuf_size_uint32_field(obj->adx_slot_type, 3);
    }
    if (obj->__has_banner
            && obj->banner != NULL)
    {
        n = ngx_com_request_adx_slot_banner__size(obj->banner);
        size += ngx_protobuf_size_message_field(n, 4);
    }
    if (obj->__has_native
            && obj->native != NULL)
    {
        n = ngx_com_request_adx_slot_native__size(obj->native);
        size += ngx_protobuf_size_message_field(n, 5);
    }
    if (obj->__has_video
            && obj->video != NULL)
    {
        n = ngx_com_request_adx_slot_video__size(obj->video);
        size += ngx_protobuf_size_message_field(n, 6);
    }
    if (obj->__has_price_floor) {
        size += ngx_protobuf_size_uint32_field(obj->price_floor, 7);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_adx_slot__pack(
        ngx_com_request_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_adx_slot__size(obj);
    size_t     n;
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_adx_slot_id) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->adx_slot_id,
                1);
    }
    if (obj->__has_adx_slot_sequence_id) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->adx_slot_sequence_id,
                2);
    }
    if (obj->__has_adx_slot_type) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->adx_slot_type,
                3);
    }
    if (obj->__has_banner
            && obj->banner != NULL)
    {
        n = ngx_com_request_adx_slot_banner__size(obj->banner);
        ctx->buffer.pos = ngx_protobuf_write_message_header(
                ctx->buffer.pos, n, 4);
        ngx_com_request_adx_slot_banner__pack(obj->banner, ctx);
    }
    if (obj->__has_native
            && obj->native != NULL)
    {
        n = ngx_com_request_adx_slot_native__size(obj->native);
        ctx->buffer.pos = ngx_protobuf_write_message_header(
                ctx->buffer.pos, n, 5);
        ngx_com_request_adx_slot_native__pack(obj->native, ctx);
    }
    if (obj->__has_video
            && obj->video != NULL)
    {
        n = ngx_com_request_adx_slot_video__size(obj->video);
        ctx->buffer.pos = ngx_protobuf_write_message_header(
                ctx->buffer.pos, n, 6);
        ngx_com_request_adx_slot_video__pack(obj->video, ctx);
    }
    if (obj->__has_price_floor) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->price_floor,
                7);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.Device.DeviceID message methods */

    ngx_int_t
ngx_com_request_device_device_id__is_initialized(
        ngx_com_request_device_device_id_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_request_device_device_id__unpack(
        ngx_com_request_device_device_id_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.Device.DeviceID.id */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->id,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.Device.DeviceID.type */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->type) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_type = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_device_device_id__size(
        ngx_com_request_device_device_id_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_id) {
        size += ngx_protobuf_size_string_field(&obj->id, 1);
    }
    if (obj->__has_type) {
        size += ngx_protobuf_size_uint32_field(obj->type, 2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_device_device_id__pack(
        ngx_com_request_device_device_id_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_device_device_id__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_id) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->id,
                1);
    }
    if (obj->__has_type) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->type,
                2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.Device field methods */

    ngx_com_request_device_device_id_t *
ngx_com_request_device__add__device_id(
        ngx_com_request_device_t *obj,
        ngx_pool_t *pool)
{
    ngx_com_request_device_device_id_t *ret;

    ret = ngx_protobuf_push_array(&obj->device_id, pool,
            sizeof(ngx_com_request_device_device_id_t));
    if (ret != NULL) {
        obj->__has_device_id = 1;
    }

    return ret;
}

/* ComRequest.Device message methods */

    ngx_int_t
ngx_com_request_device__is_initialized(
        ngx_com_request_device_t *obj)
{
    return 1; /* no required fields */
}

    static ngx_int_t
ngx_com_request_device__unpack_device_id(
        ngx_com_request_device_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    ngx_com_request_device_device_id_t  *fptr;
    u_char                              *end0;
    u_char                              *end;
    ngx_int_t                            rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    fptr = ngx_com_request_device__add__device_id(obj, ctx->pool);
    if (fptr == NULL) {
        return NGX_ERROR;
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_device_device_id__unpack(fptr, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_device_id = 1;
    }

    return rc;
}

    ngx_int_t
ngx_com_request_device__unpack(
        ngx_com_request_device_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    uint32_t      mlen;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.Device.device_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request_device__unpack_device_id(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.Device.device_type */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->device_type) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_device_type = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComRequest.Device.os */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->os) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_os = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComRequest.Device.os_version */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->os_version,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_os_version = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 5: /* ComRequest.Device.carrier */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->carrier) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_carrier = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 6: /* ComRequest.Device.connection */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->connection) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_connection = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 7: /* ComRequest.Device.brand */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->brand,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_brand = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 8: /* ComRequest.Device.model */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->model,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_model = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 9: /* ComRequest.Device.user_agent */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->user_agent,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_user_agent = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 10: /* ComRequest.Device.ip */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->ip,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_ip = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_device__size(
        ngx_com_request_device_t *obj)
{
    size_t      size = 0;
    size_t      n;
    ngx_uint_t  i;

    if (obj->__has_device_id
            && obj->device_id != NULL
            && obj->device_id->nelts > 0)
    {
        ngx_com_request_device_device_id_t *vals = obj->device_id->elts;

        for (i = 0; i < obj->device_id->nelts; ++i) {
            n = ngx_com_request_device_device_id__size(vals + i);
            size += ngx_protobuf_size_message_field(n, 1);
        }
    }
    if (obj->__has_device_type) {
        size += ngx_protobuf_size_uint32_field(obj->device_type, 2);
    }
    if (obj->__has_os) {
        size += ngx_protobuf_size_uint32_field(obj->os, 3);
    }
    if (obj->__has_os_version) {
        size += ngx_protobuf_size_string_field(&obj->os_version, 4);
    }
    if (obj->__has_carrier) {
        size += ngx_protobuf_size_uint32_field(obj->carrier, 5);
    }
    if (obj->__has_connection) {
        size += ngx_protobuf_size_uint32_field(obj->connection, 6);
    }
    if (obj->__has_brand) {
        size += ngx_protobuf_size_string_field(&obj->brand, 7);
    }
    if (obj->__has_model) {
        size += ngx_protobuf_size_string_field(&obj->model, 8);
    }
    if (obj->__has_user_agent) {
        size += ngx_protobuf_size_string_field(&obj->user_agent, 9);
    }
    if (obj->__has_ip) {
        size += ngx_protobuf_size_string_field(&obj->ip, 10);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_device__pack(
        ngx_com_request_device_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_device__size(obj);
    size_t     n;
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_device_id
            && obj->device_id != NULL
            && obj->device_id->nelts > 0)
    {
        ngx_com_request_device_device_id_t *vals = obj->device_id->elts;
        ngx_uint_t i;

        for (i = 0; i < obj->device_id->nelts; ++i) {
            n = ngx_com_request_device_device_id__size(vals + i);
            ctx->buffer.pos = ngx_protobuf_write_message_header(
                    ctx->buffer.pos, n, 1);
            ngx_com_request_device_device_id__pack(vals + i, ctx);
        }
    }
    if (obj->__has_device_type) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->device_type,
                2);
    }
    if (obj->__has_os) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->os,
                3);
    }
    if (obj->__has_os_version) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->os_version,
                4);
    }
    if (obj->__has_carrier) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->carrier,
                5);
    }
    if (obj->__has_connection) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->connection,
                6);
    }
    if (obj->__has_brand) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->brand,
                7);
    }
    if (obj->__has_model) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->model,
                8);
    }
    if (obj->__has_user_agent) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->user_agent,
                9);
    }
    if (obj->__has_ip) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->ip,
                10);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest.App message methods */

    ngx_int_t
ngx_com_request_app__is_initialized(
        ngx_com_request_app_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_request_app__unpack(
        ngx_com_request_app_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.App.app_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->app_id,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_app_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.App.app_category */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->app_category) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_app_category = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request_app__size(
        ngx_com_request_app_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_app_id) {
        size += ngx_protobuf_size_string_field(&obj->app_id, 1);
    }
    if (obj->__has_app_category) {
        size += ngx_protobuf_size_uint32_field(obj->app_category, 2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request_app__pack(
        ngx_com_request_app_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request_app__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_app_id) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->app_id,
                1);
    }
    if (obj->__has_app_category) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->app_category,
                2);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComRequest field methods */

    ngx_com_request_adx_slot_t *
ngx_com_request__add__adx_slot(
        ngx_com_request_t *obj,
        ngx_pool_t *pool)
{
    ngx_com_request_adx_slot_t *ret;

    ret = ngx_protobuf_push_array(&obj->adx_slot, pool,
            sizeof(ngx_com_request_adx_slot_t));
    if (ret != NULL) {
        obj->__has_adx_slot = 1;
    }

    return ret;
}

/* ComRequest message methods */

    ngx_int_t
ngx_com_request__is_initialized(
        ngx_com_request_t *obj)
{
    return 1; /* no required fields */
}

    static ngx_int_t
ngx_com_request__unpack_adx_slot(
        ngx_com_request_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    ngx_com_request_adx_slot_t  *fptr;
    u_char                      *end0;
    u_char                      *end;
    ngx_int_t                    rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    fptr = ngx_com_request__add__adx_slot(obj, ctx->pool);
    if (fptr == NULL) {
        return NGX_ERROR;
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_adx_slot__unpack(fptr, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_adx_slot = 1;
    }

    return rc;
}

    static ngx_int_t
ngx_com_request__unpack_device(
        ngx_com_request_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    u_char     *end0;
    u_char     *end;
    ngx_int_t   rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->device != NULL) {
        ngx_com_request_device__clear(obj->device);
    } else {
        if (ctx->pool != NULL) {
            obj->device = ngx_com_request_device__alloc(ctx->pool);
        }
        if (obj->device == NULL) {
            return NGX_ERROR;
        }
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_device__unpack(obj->device, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_device = 1;
    }

    return rc;
}

    static ngx_int_t
ngx_com_request__unpack_app(
        ngx_com_request_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    u_char     *end0;
    u_char     *end;
    ngx_int_t   rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->app != NULL) {
        ngx_com_request_app__clear(obj->app);
    } else {
        if (ctx->pool != NULL) {
            obj->app = ngx_com_request_app__alloc(ctx->pool);
        }
        if (obj->app == NULL) {
            return NGX_ERROR;
        }
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_request_app__unpack(obj->app, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_app = 1;
    }

    return rc;
}

    ngx_int_t
ngx_com_request__unpack(
        ngx_com_request_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    uint32_t      mlen;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComRequest.adx */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->adx) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComRequest.bid */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->bid,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_bid = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComRequest.adx_slot */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request__unpack_adx_slot(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComRequest.device */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request__unpack_device(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 5: /* ComRequest.app */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_request__unpack_app(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_request__size(
        ngx_com_request_t *obj)
{
    size_t      size = 0;
    size_t      n;
    ngx_uint_t  i;

    if (obj->__has_adx) {
        size += ngx_protobuf_size_uint32_field(obj->adx, 1);
    }
    if (obj->__has_bid) {
        size += ngx_protobuf_size_string_field(&obj->bid, 2);
    }
    if (obj->__has_adx_slot
            && obj->adx_slot != NULL
            && obj->adx_slot->nelts > 0)
    {
        ngx_com_request_adx_slot_t *vals = obj->adx_slot->elts;

        for (i = 0; i < obj->adx_slot->nelts; ++i) {
            n = ngx_com_request_adx_slot__size(vals + i);
            size += ngx_protobuf_size_message_field(n, 3);
        }
    }
    if (obj->__has_device
            && obj->device != NULL)
    {
        n = ngx_com_request_device__size(obj->device);
        size += ngx_protobuf_size_message_field(n, 4);
    }
    if (obj->__has_app
            && obj->app != NULL)
    {
        n = ngx_com_request_app__size(obj->app);
        size += ngx_protobuf_size_message_field(n, 5);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_request__pack(
        ngx_com_request_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_request__size(obj);
    size_t     n;
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_adx) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->adx,
                1);
    }
    if (obj->__has_bid) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->bid,
                2);
    }
    if (obj->__has_adx_slot
            && obj->adx_slot != NULL
            && obj->adx_slot->nelts > 0)
    {
        ngx_com_request_adx_slot_t *vals = obj->adx_slot->elts;
        ngx_uint_t i;

        for (i = 0; i < obj->adx_slot->nelts; ++i) {
            n = ngx_com_request_adx_slot__size(vals + i);
            ctx->buffer.pos = ngx_protobuf_write_message_header(
                    ctx->buffer.pos, n, 3);
            ngx_com_request_adx_slot__pack(vals + i, ctx);
        }
    }
    if (obj->__has_device
            && obj->device != NULL)
    {
        n = ngx_com_request_device__size(obj->device);
        ctx->buffer.pos = ngx_protobuf_write_message_header(
                ctx->buffer.pos, n, 4);
        ngx_com_request_device__pack(obj->device, ctx);
    }
    if (obj->__has_app
            && obj->app != NULL)
    {
        n = ngx_com_request_app__size(obj->app);
        ctx->buffer.pos = ngx_protobuf_write_message_header(
                ctx->buffer.pos, n, 5);
        ngx_com_request_app__pack(obj->app, ctx);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComResponse.AdxSlot message methods */

    ngx_int_t
ngx_com_response_adx_slot__is_initialized(
        ngx_com_response_adx_slot_t *obj)
{
    return 1; /* no required fields */
}

    ngx_int_t
ngx_com_response_adx_slot__unpack(
        ngx_com_response_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    // uint32_t      u32v;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComResponse.AdxSlot.adx_slot_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->adx_slot_id,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComResponse.AdxSlot.adx_slot_sequence_id */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->adx_slot_sequence_id) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_sequence_id = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 3: /* ComResponse.AdxSlot.adx_slot_type */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->adx_slot_type) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_adx_slot_type = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 4: /* ComResponse.AdxSlot.price */
                if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                    if (ngx_protobuf_read_uint32(pos, end,
                                (uint32_t *)&obj->price) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_price = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 5: /* ComResponse.AdxSlot.template */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->template,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_template = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 6: /* ComResponse.AdxSlot.ext */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->ext,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_ext = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_response_adx_slot__size(
        ngx_com_response_adx_slot_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_adx_slot_id) {
        size += ngx_protobuf_size_string_field(&obj->adx_slot_id, 1);
    }
    if (obj->__has_adx_slot_sequence_id) {
        size += ngx_protobuf_size_uint32_field(obj->adx_slot_sequence_id, 2);
    }
    if (obj->__has_adx_slot_type) {
        size += ngx_protobuf_size_uint32_field(obj->adx_slot_type, 3);
    }
    if (obj->__has_price) {
        size += ngx_protobuf_size_uint32_field(obj->price, 4);
    }
    if (obj->__has_template) {
        size += ngx_protobuf_size_string_field(&obj->template, 5);
    }
    if (obj->__has_ext) {
        size += ngx_protobuf_size_string_field(&obj->ext, 6);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_response_adx_slot__pack(
        ngx_com_response_adx_slot_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_response_adx_slot__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_adx_slot_id) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->adx_slot_id,
                1);
    }
    if (obj->__has_adx_slot_sequence_id) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->adx_slot_sequence_id,
                2);
    }
    if (obj->__has_adx_slot_type) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->adx_slot_type,
                3);
    }
    if (obj->__has_price) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
                ctx->buffer.pos,
                obj->price,
                4);
    }
    if (obj->__has_template) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->template,
                5);
    }
    if (obj->__has_ext) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->ext,
                6);
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ComResponse field methods */

    ngx_com_response_adx_slot_t *
ngx_com_response__add__adx_slot(
        ngx_com_response_t *obj,
        ngx_pool_t *pool)
{
    ngx_com_response_adx_slot_t *ret;

    ret = ngx_protobuf_push_array(&obj->adx_slot, pool,
            sizeof(ngx_com_response_adx_slot_t));
    if (ret != NULL) {
        obj->__has_adx_slot = 1;
    }

    return ret;
}

/* ComResponse message methods */

    ngx_int_t
ngx_com_response__is_initialized(
        ngx_com_response_t *obj)
{
    return 1; /* no required fields */
}

    static ngx_int_t
ngx_com_response__unpack_adx_slot(
        ngx_com_response_t *obj,
        ngx_protobuf_context_t *ctx,
        size_t len)
{
    ngx_com_response_adx_slot_t  *fptr;
    u_char                       *end0;
    u_char                       *end;
    ngx_int_t                     rc;

    if (len == 0) {
        return NGX_OK;
    }

    end = ctx->buffer.pos + len;
    if (end > ctx->buffer.last) {
        return NGX_ABORT;
    }

    fptr = ngx_com_response__add__adx_slot(obj, ctx->pool);
    if (fptr == NULL) {
        return NGX_ERROR;
    }

    end0 = ctx->buffer.last;
    ctx->buffer.last = end;
    rc = ngx_com_response_adx_slot__unpack(fptr, ctx);
    ctx->buffer.last = end0;

    if (rc == NGX_OK) {
        obj->__has_adx_slot = 1;
    }

    return rc;
}

    ngx_int_t
ngx_com_response__unpack(
        ngx_com_response_t *obj,
        ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    ngx_pool_t   *pool = ctx->pool;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    uint32_t      mlen;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
            case 1: /* ComResponse.bid */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_string(pos, end,
                                &obj->bid,
                                (ctx->reuse_strings) ? NULL : pool) != NGX_OK)
                    {
                        return NGX_ABORT;
                    }
                    obj->__has_bid = 1;
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            case 2: /* ComResponse.adx_slot */
                if (wire == NGX_PROTOBUF_WIRETYPE_LENGTH_DELIMITED) {
                    if (ngx_protobuf_read_uint32(pos, end, &mlen) != NGX_OK) {
                        return NGX_ABORT;
                    }
                    rc = ngx_com_response__unpack_adx_slot(obj, ctx, mlen);
                    if (rc != NGX_OK) {
                        return rc;
                    }
                } else {
                    if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                        return NGX_ABORT;
                    }
                }
                break;
            default:
                rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                        &obj->__unknown);
                if (rc != NGX_OK) {
                    return rc;
                }
                break;
        }
    }

    return NGX_OK;
}

    size_t
ngx_com_response__size(
        ngx_com_response_t *obj)
{
    size_t      size = 0;
    size_t      n;
    ngx_uint_t  i;

    if (obj->__has_bid) {
        size += ngx_protobuf_size_string_field(&obj->bid, 1);
    }
    if (obj->__has_adx_slot
            && obj->adx_slot != NULL
            && obj->adx_slot->nelts > 0)
    {
        ngx_com_response_adx_slot_t *vals = obj->adx_slot->elts;

        for (i = 0; i < obj->adx_slot->nelts; ++i) {
            n = ngx_com_response_adx_slot__size(vals + i);
            size += ngx_protobuf_size_message_field(n, 2);
        }
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

    ngx_int_t
ngx_com_response__pack(
        ngx_com_response_t *obj,
        ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_com_response__size(obj);
    size_t     n;
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_bid) {
        ctx->buffer.pos = ngx_protobuf_write_string_field(
                ctx->buffer.pos,
                &obj->bid,
                1);
    }
    if (obj->__has_adx_slot
            && obj->adx_slot != NULL
            && obj->adx_slot->nelts > 0)
    {
        ngx_com_response_adx_slot_t *vals = obj->adx_slot->elts;
        ngx_uint_t i;

        for (i = 0; i < obj->adx_slot->nelts; ++i) {
            n = ngx_com_response_adx_slot__size(vals + i);
            ctx->buffer.pos = ngx_protobuf_write_message_header(
                    ctx->buffer.pos, n, 2);
            ngx_com_response_adx_slot__pack(vals + i, ctx);
        }
    }

    if (obj->__unknown != NULL
            && obj->__unknown->elts != NULL
            && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

