/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */

#ifndef _NGX_ADX_COM_PROTO_H_INCLUDED_
#define _NGX_ADX_COM_PROTO_H_INCLUDED_

#include <stdint.h>
#include <ngx_config.h>
#include <ngx_string.h>
#include <ngx_array.h>
#include <ngx_palloc.h>
#include <ngx_rbtree.h>
#include <ngx_protobuf.h>

/* ComRequest.AdxSlot.AdxSlotType */

typedef enum {
    NGX_COMREQUEST_ADXSLOT_ADX_SLOT_UNKNOWN = 0,
    NGX_COMREQUEST_ADXSLOT_ADX_SLOT_BANNER  = 1,
    NGX_COMREQUEST_ADXSLOT_ADX_SLOT_NATIVE  = 2,
    NGX_COMREQUEST_ADXSLOT_ADX_SLOT_VIDEO   = 3
} ngx_com_request_adx_slot_adx_slot_type_e;

/* ComRequest.AdxSlot.Banner */

typedef struct {
    int32_t      width;
    int32_t      height;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_width  : 1;
    uint32_t     __has_height : 1;
} ngx_com_request_adx_slot_banner_t;

/* ComRequest.AdxSlot.Native */

typedef struct {
    int32_t      icon_width;
    int32_t      icon_height;
    int32_t      width;
    int32_t      height;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_icon_width  : 1;
    uint32_t     __has_icon_height : 1;
    uint32_t     __has_width       : 1;
    uint32_t     __has_height      : 1;
} ngx_com_request_adx_slot_native_t;

/* ComRequest.AdxSlot.Video */

typedef struct {
    int32_t      width;
    int32_t      height;
    int32_t      min_duration;
    int32_t      max_duration;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_width        : 1;
    uint32_t     __has_height       : 1;
    uint32_t     __has_min_duration : 1;
    uint32_t     __has_max_duration : 1;
} ngx_com_request_adx_slot_video_t;

/* ComRequest.AdxSlot */

typedef struct {
    ngx_str_t                                 adx_slot_id;
    int32_t                                   adx_slot_sequence_id;
    ngx_com_request_adx_slot_adx_slot_type_e  adx_slot_type;
    ngx_com_request_adx_slot_banner_t        *banner;
    ngx_com_request_adx_slot_native_t        *native;
    ngx_com_request_adx_slot_video_t         *video;
    int32_t                                   price_floor;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t                              *__unknown;
    uint32_t                                  __has_adx_slot_id          : 1;
    uint32_t                                  __has_adx_slot_sequence_id : 1;
    uint32_t                                  __has_adx_slot_type        : 1;
    uint32_t                                  __has_banner               : 1;
    uint32_t                                  __has_native               : 1;
    uint32_t                                  __has_video                : 1;
    uint32_t                                  __has_price_floor          : 1;
} ngx_com_request_adx_slot_t;

/* ComRequest.Device.DeviceIdType */

typedef enum {
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_UNKNOW          =  0,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IMEI            =  1,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IMEI_SHA1       =  2,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IMEI_MD5        =  3,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_ANDROID_ID      =  4,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_ANDROID_ID_SHA1 =  5,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_ANDROID_ID_MD5  =  6,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IDFA            =  7,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IDFA_SHA1       =  8,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_IDFA_MD5        =  9,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_MAC             = 10,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_MAC_SHA1        = 11,
    NGX_COMREQUEST_DEVICE_ADX_DEVICEID_MAC_MD5         = 12
} ngx_com_request_device_device_id_type_e;

/* ComRequest.Device.DeviceType */

typedef enum {
    NGX_COMREQUEST_DEVICE_ADX_DEVICE_UNKNOWN = 0,
    NGX_COMREQUEST_DEVICE_ADX_DEVICE_MOBILE  = 1,
    NGX_COMREQUEST_DEVICE_ADX_DEVICE_PAD     = 2,
    NGX_COMREQUEST_DEVICE_ADX_DEVICE_PC      = 3
} ngx_com_request_device_device_type_e;

/* ComRequest.Device.OS */

typedef enum {
    NGX_COMREQUEST_DEVICE_ADX_OS_UNKNOWN = 0,
    NGX_COMREQUEST_DEVICE_ADX_OS_IOS     = 1,
    NGX_COMREQUEST_DEVICE_ADX_OS_ANDROID = 2,
    NGX_COMREQUEST_DEVICE_ADX_OS_WINDOWS = 3
} ngx_com_request_device_os_e;

/* ComRequest.Device.Carrier */

typedef enum {
    NGX_COMREQUEST_DEVICE_ADX_CARRIER_UNKNOWN       = 0,
    NGX_COMREQUEST_DEVICE_ADX_CARRIER_CHINA_MOBILE  = 1,
    NGX_COMREQUEST_DEVICE_ADX_CARRIER_CHINA_UNICOM  = 2,
    NGX_COMREQUEST_DEVICE_ADX_CARRIER_CHINA_TELECOM = 3
} ngx_com_request_device_carrier_e;

/* ComRequest.Device.Connection */

typedef enum {
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_UNKNOWN = 0,
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_WIFI    = 1,
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_2G      = 2,
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_3G      = 3,
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_4G      = 4,
    NGX_COMREQUEST_DEVICE_ADX_CONNECTION_5G      = 5
} ngx_com_request_device_connection_e;

/* ComRequest.Device.DeviceID */

typedef struct {
    ngx_str_t                                id;
    ngx_com_request_device_device_id_type_e  type;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t                             *__unknown;
    uint32_t                                 __has_id   : 1;
    uint32_t                                 __has_type : 1;
} ngx_com_request_device_device_id_t;

/* ComRequest.Device */

typedef struct {
    /* ngx_com_request_device_device_id_t */
    ngx_array_t                          *device_id;
    ngx_com_request_device_device_type_e  device_type;
    ngx_com_request_device_os_e           os;
    ngx_str_t                             os_version;
    ngx_com_request_device_carrier_e      carrier;
    ngx_com_request_device_connection_e   connection;
    ngx_str_t                             brand;
    ngx_str_t                             model;
    ngx_str_t                             user_agent;
    ngx_str_t                             ip;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t                          *__unknown;
    uint32_t                              __has_device_id   : 1;
    uint32_t                              __has_device_type : 1;
    uint32_t                              __has_os          : 1;
    uint32_t                              __has_os_version  : 1;
    uint32_t                              __has_carrier     : 1;
    uint32_t                              __has_connection  : 1;
    uint32_t                              __has_brand       : 1;
    uint32_t                              __has_model       : 1;
    uint32_t                              __has_user_agent  : 1;
    uint32_t                              __has_ip          : 1;
} ngx_com_request_device_t;

/* ComRequest.App */

typedef struct {
    ngx_str_t    app_id;
    int32_t      app_category;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_app_id       : 1;
    uint32_t     __has_app_category : 1;
} ngx_com_request_app_t;

/* ComRequest */

typedef struct {
    int32_t                   adx;
    ngx_str_t                 bid;
    /* ngx_com_request_adx_slot_t */
    ngx_array_t              *adx_slot;
    ngx_com_request_device_t *device;
    ngx_com_request_app_t    *app;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t              *__unknown;
    uint32_t                  __has_adx      : 1;
    uint32_t                  __has_bid      : 1;
    uint32_t                  __has_adx_slot : 1;
    uint32_t                  __has_device   : 1;
    uint32_t                  __has_app      : 1;
} ngx_com_request_t;

/* ComResponse.AdxSlot.AdxSlotType */

typedef enum {
    NGX_COMRESPONSE_ADXSLOT_ADX_SLOT_UNKNOWN = 0,
    NGX_COMRESPONSE_ADXSLOT_ADX_SLOT_BANNER  = 1,
    NGX_COMRESPONSE_ADXSLOT_ADX_SLOT_NATIVE  = 2,
    NGX_COMRESPONSE_ADXSLOT_ADX_SLOT_VIDEO   = 3
} ngx_com_response_adx_slot_adx_slot_type_e;

/* ComResponse.AdxSlot */

typedef struct {
    ngx_str_t                                  adx_slot_id;
    int32_t                                    adx_slot_sequence_id;
    ngx_com_response_adx_slot_adx_slot_type_e  adx_slot_type;
    int32_t                                    price;
    ngx_str_t                                  template;
    ngx_str_t                                  ext;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t                               *__unknown;
    uint32_t                                   __has_adx_slot_id          : 1;
    uint32_t                                   __has_adx_slot_sequence_id : 1;
    uint32_t                                   __has_adx_slot_type        : 1;
    uint32_t                                   __has_price                : 1;
    uint32_t                                   __has_template             : 1;
    uint32_t                                   __has_ext                  : 1;
} ngx_com_response_adx_slot_t;

/* ComResponse */

typedef struct {
    ngx_str_t    bid;
    /* ngx_com_response_adx_slot_t */
    ngx_array_t *adx_slot;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_bid      : 1;
    uint32_t     __has_adx_slot : 1;
} ngx_com_response_t;

/* ComRequest.AdxSlot.Banner field methods */

#define ngx_com_request_adx_slot_banner__set_width(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, width, val)

#define ngx_com_request_adx_slot_banner__clear_width(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, width)

#define ngx_com_request_adx_slot_banner__has_width(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, width))

#define ngx_com_request_adx_slot_banner__set_height(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, height, val)

#define ngx_com_request_adx_slot_banner__clear_height(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, height)

#define ngx_com_request_adx_slot_banner__has_height(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, height))

/* ComRequest.AdxSlot.Banner message methods */

#define ngx_com_request_adx_slot_banner__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_adx_slot_banner_t))

#define ngx_com_request_adx_slot_banner__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_adx_slot_banner_t))

ngx_int_t ngx_com_request_adx_slot_banner__is_initialized(
    ngx_com_request_adx_slot_banner_t *obj);

ngx_int_t ngx_com_request_adx_slot_banner__unpack(
    ngx_com_request_adx_slot_banner_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_adx_slot_banner__size(
    ngx_com_request_adx_slot_banner_t *obj);

ngx_int_t ngx_com_request_adx_slot_banner__pack(
    ngx_com_request_adx_slot_banner_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.AdxSlot.Native field methods */

#define ngx_com_request_adx_slot_native__set_icon_width(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, icon_width, val)

#define ngx_com_request_adx_slot_native__clear_icon_width(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, icon_width)

#define ngx_com_request_adx_slot_native__has_icon_width(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, icon_width))

#define ngx_com_request_adx_slot_native__set_icon_height(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, icon_height, val)

#define ngx_com_request_adx_slot_native__clear_icon_height(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, icon_height)

#define ngx_com_request_adx_slot_native__has_icon_height(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, icon_height))

#define ngx_com_request_adx_slot_native__set_width(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, width, val)

#define ngx_com_request_adx_slot_native__clear_width(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, width)

#define ngx_com_request_adx_slot_native__has_width(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, width))

#define ngx_com_request_adx_slot_native__set_height(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, height, val)

#define ngx_com_request_adx_slot_native__clear_height(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, height)

#define ngx_com_request_adx_slot_native__has_height(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, height))

/* ComRequest.AdxSlot.Native message methods */

#define ngx_com_request_adx_slot_native__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_adx_slot_native_t))

#define ngx_com_request_adx_slot_native__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_adx_slot_native_t))

ngx_int_t ngx_com_request_adx_slot_native__is_initialized(
    ngx_com_request_adx_slot_native_t *obj);

ngx_int_t ngx_com_request_adx_slot_native__unpack(
    ngx_com_request_adx_slot_native_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_adx_slot_native__size(
    ngx_com_request_adx_slot_native_t *obj);

ngx_int_t ngx_com_request_adx_slot_native__pack(
    ngx_com_request_adx_slot_native_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.AdxSlot.Video field methods */

#define ngx_com_request_adx_slot_video__set_width(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, width, val)

#define ngx_com_request_adx_slot_video__clear_width(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, width)

#define ngx_com_request_adx_slot_video__has_width(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, width))

#define ngx_com_request_adx_slot_video__set_height(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, height, val)

#define ngx_com_request_adx_slot_video__clear_height(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, height)

#define ngx_com_request_adx_slot_video__has_height(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, height))

#define ngx_com_request_adx_slot_video__set_min_duration(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, min_duration, val)

#define ngx_com_request_adx_slot_video__clear_min_duration(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, min_duration)

#define ngx_com_request_adx_slot_video__has_min_duration(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, min_duration))

#define ngx_com_request_adx_slot_video__set_max_duration(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, max_duration, val)

#define ngx_com_request_adx_slot_video__clear_max_duration(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, max_duration)

#define ngx_com_request_adx_slot_video__has_max_duration(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, max_duration))

/* ComRequest.AdxSlot.Video message methods */

#define ngx_com_request_adx_slot_video__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_adx_slot_video_t))

#define ngx_com_request_adx_slot_video__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_adx_slot_video_t))

ngx_int_t ngx_com_request_adx_slot_video__is_initialized(
    ngx_com_request_adx_slot_video_t *obj);

ngx_int_t ngx_com_request_adx_slot_video__unpack(
    ngx_com_request_adx_slot_video_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_adx_slot_video__size(
    ngx_com_request_adx_slot_video_t *obj);

ngx_int_t ngx_com_request_adx_slot_video__pack(
    ngx_com_request_adx_slot_video_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.AdxSlot field methods */

#define ngx_com_request_adx_slot__set_adx_slot_id(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, adx_slot_id, val)

#define ngx_com_request_adx_slot__clear_adx_slot_id(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, adx_slot_id)

#define ngx_com_request_adx_slot__has_adx_slot_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_id))

#define ngx_com_request_adx_slot__set_adx_slot_sequence_id(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, adx_slot_sequence_id, val)

#define ngx_com_request_adx_slot__clear_adx_slot_sequence_id(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, adx_slot_sequence_id)

#define ngx_com_request_adx_slot__has_adx_slot_sequence_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_sequence_id))

#define ngx_com_request_adx_slot__set_adx_slot_type(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, adx_slot_type, val)

#define ngx_com_request_adx_slot__clear_adx_slot_type(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, adx_slot_type)

#define ngx_com_request_adx_slot__has_adx_slot_type(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_type))

#define ngx_com_request_adx_slot__set_banner(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, banner, val)

#define ngx_com_request_adx_slot__clear_banner(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, banner)

#define ngx_com_request_adx_slot__has_banner(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, banner))

#define ngx_com_request_adx_slot__set_native(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, native, val)

#define ngx_com_request_adx_slot__clear_native(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, native)

#define ngx_com_request_adx_slot__has_native(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, native))

#define ngx_com_request_adx_slot__set_video(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, video, val)

#define ngx_com_request_adx_slot__clear_video(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, video)

#define ngx_com_request_adx_slot__has_video(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, video))

#define ngx_com_request_adx_slot__set_price_floor(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, price_floor, val)

#define ngx_com_request_adx_slot__clear_price_floor(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, price_floor)

#define ngx_com_request_adx_slot__has_price_floor(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, price_floor))

/* ComRequest.AdxSlot message methods */

#define ngx_com_request_adx_slot__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_adx_slot_t))

#define ngx_com_request_adx_slot__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_adx_slot_t))

ngx_int_t ngx_com_request_adx_slot__is_initialized(
    ngx_com_request_adx_slot_t *obj);

ngx_int_t ngx_com_request_adx_slot__unpack(
    ngx_com_request_adx_slot_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_adx_slot__size(
    ngx_com_request_adx_slot_t *obj);

ngx_int_t ngx_com_request_adx_slot__pack(
    ngx_com_request_adx_slot_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.Device.DeviceID field methods */

#define ngx_com_request_device_device_id__set_id(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, id, val)

#define ngx_com_request_device_device_id__clear_id(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, id)

#define ngx_com_request_device_device_id__has_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, id))

#define ngx_com_request_device_device_id__set_type(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, type, val)

#define ngx_com_request_device_device_id__clear_type(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, type)

#define ngx_com_request_device_device_id__has_type(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, type))

/* ComRequest.Device.DeviceID message methods */

#define ngx_com_request_device_device_id__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_device_device_id_t))

#define ngx_com_request_device_device_id__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_device_device_id_t))

ngx_int_t ngx_com_request_device_device_id__is_initialized(
    ngx_com_request_device_device_id_t *obj);

ngx_int_t ngx_com_request_device_device_id__unpack(
    ngx_com_request_device_device_id_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_device_device_id__size(
    ngx_com_request_device_device_id_t *obj);

ngx_int_t ngx_com_request_device_device_id__pack(
    ngx_com_request_device_device_id_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.Device field methods */

#define ngx_com_request_device__set_device_id(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, device_id, val)

ngx_com_request_device_device_id_t *
ngx_com_request_device__add__device_id(
    ngx_com_request_device_t *obj,
    ngx_pool_t *pool);

#define ngx_com_request_device__clear_device_id(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, device_id)

#define ngx_com_request_device__has_device_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, device_id) && \
     (obj)->device_id->nelts > 0)

#define ngx_com_request_device__set_device_type(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, device_type, val)

#define ngx_com_request_device__clear_device_type(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, device_type)

#define ngx_com_request_device__has_device_type(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, device_type))

#define ngx_com_request_device__set_os(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, os, val)

#define ngx_com_request_device__clear_os(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, os)

#define ngx_com_request_device__has_os(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, os))

#define ngx_com_request_device__set_os_version(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, os_version, val)

#define ngx_com_request_device__clear_os_version(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, os_version)

#define ngx_com_request_device__has_os_version(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, os_version))

#define ngx_com_request_device__set_carrier(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, carrier, val)

#define ngx_com_request_device__clear_carrier(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, carrier)

#define ngx_com_request_device__has_carrier(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, carrier))

#define ngx_com_request_device__set_connection(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, connection, val)

#define ngx_com_request_device__clear_connection(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, connection)

#define ngx_com_request_device__has_connection(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, connection))

#define ngx_com_request_device__set_brand(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, brand, val)

#define ngx_com_request_device__clear_brand(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, brand)

#define ngx_com_request_device__has_brand(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, brand))

#define ngx_com_request_device__set_model(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, model, val)

#define ngx_com_request_device__clear_model(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, model)

#define ngx_com_request_device__has_model(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, model))

#define ngx_com_request_device__set_user_agent(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, user_agent, val)

#define ngx_com_request_device__clear_user_agent(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, user_agent)

#define ngx_com_request_device__has_user_agent(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, user_agent))

#define ngx_com_request_device__set_ip(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, ip, val)

#define ngx_com_request_device__clear_ip(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, ip)

#define ngx_com_request_device__has_ip(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, ip))

/* ComRequest.Device message methods */

#define ngx_com_request_device__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_device_t))

#define ngx_com_request_device__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_device_t))

ngx_int_t ngx_com_request_device__is_initialized(
    ngx_com_request_device_t *obj);

ngx_int_t ngx_com_request_device__unpack(
    ngx_com_request_device_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_device__size(
    ngx_com_request_device_t *obj);

ngx_int_t ngx_com_request_device__pack(
    ngx_com_request_device_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest.App field methods */

#define ngx_com_request_app__set_app_id(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, app_id, val)

#define ngx_com_request_app__clear_app_id(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, app_id)

#define ngx_com_request_app__has_app_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, app_id))

#define ngx_com_request_app__set_app_category(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, app_category, val)

#define ngx_com_request_app__clear_app_category(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, app_category)

#define ngx_com_request_app__has_app_category(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, app_category))

/* ComRequest.App message methods */

#define ngx_com_request_app__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_app_t))

#define ngx_com_request_app__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_app_t))

ngx_int_t ngx_com_request_app__is_initialized(
    ngx_com_request_app_t *obj);

ngx_int_t ngx_com_request_app__unpack(
    ngx_com_request_app_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request_app__size(
    ngx_com_request_app_t *obj);

ngx_int_t ngx_com_request_app__pack(
    ngx_com_request_app_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComRequest field methods */

#define ngx_com_request__set_adx(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, adx, val)

#define ngx_com_request__clear_adx(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, adx)

#define ngx_com_request__has_adx(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx))

#define ngx_com_request__set_bid(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, bid, val)

#define ngx_com_request__clear_bid(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, bid)

#define ngx_com_request__has_bid(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, bid))

#define ngx_com_request__set_adx_slot(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, adx_slot, val)

ngx_com_request_adx_slot_t *
ngx_com_request__add__adx_slot(
    ngx_com_request_t *obj,
    ngx_pool_t *pool);

#define ngx_com_request__clear_adx_slot(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, adx_slot)

#define ngx_com_request__has_adx_slot(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot) && \
     (obj)->adx_slot->nelts > 0)

#define ngx_com_request__set_device(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, device, val)

#define ngx_com_request__clear_device(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, device)

#define ngx_com_request__has_device(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, device))

#define ngx_com_request__set_app(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, app, val)

#define ngx_com_request__clear_app(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, app)

#define ngx_com_request__has_app(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, app))

/* ComRequest message methods */

#define ngx_com_request__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_request_t))

#define ngx_com_request__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_request_t))

ngx_int_t ngx_com_request__is_initialized(
    ngx_com_request_t *obj);

ngx_int_t ngx_com_request__unpack(
    ngx_com_request_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_request__size(
    ngx_com_request_t *obj);

ngx_int_t ngx_com_request__pack(
    ngx_com_request_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComResponse.AdxSlot field methods */

#define ngx_com_response_adx_slot__set_adx_slot_id(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, adx_slot_id, val)

#define ngx_com_response_adx_slot__clear_adx_slot_id(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, adx_slot_id)

#define ngx_com_response_adx_slot__has_adx_slot_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_id))

#define ngx_com_response_adx_slot__set_adx_slot_sequence_id(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, adx_slot_sequence_id, val)

#define ngx_com_response_adx_slot__clear_adx_slot_sequence_id(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, adx_slot_sequence_id)

#define ngx_com_response_adx_slot__has_adx_slot_sequence_id(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_sequence_id))

#define ngx_com_response_adx_slot__set_adx_slot_type(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, adx_slot_type, val)

#define ngx_com_response_adx_slot__clear_adx_slot_type(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, adx_slot_type)

#define ngx_com_response_adx_slot__has_adx_slot_type(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot_type))

#define ngx_com_response_adx_slot__set_price(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, price, val)

#define ngx_com_response_adx_slot__clear_price(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, price)

#define ngx_com_response_adx_slot__has_price(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, price))

#define ngx_com_response_adx_slot__set_template(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, template, val)

#define ngx_com_response_adx_slot__clear_template(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, template)

#define ngx_com_response_adx_slot__has_template(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, template))

#define ngx_com_response_adx_slot__set_ext(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, ext, val)

#define ngx_com_response_adx_slot__clear_ext(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, ext)

#define ngx_com_response_adx_slot__has_ext(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, ext))

/* ComResponse.AdxSlot message methods */

#define ngx_com_response_adx_slot__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_response_adx_slot_t))

#define ngx_com_response_adx_slot__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_response_adx_slot_t))

ngx_int_t ngx_com_response_adx_slot__is_initialized(
    ngx_com_response_adx_slot_t *obj);

ngx_int_t ngx_com_response_adx_slot__unpack(
    ngx_com_response_adx_slot_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_response_adx_slot__size(
    ngx_com_response_adx_slot_t *obj);

ngx_int_t ngx_com_response_adx_slot__pack(
    ngx_com_response_adx_slot_t *obj,
    ngx_protobuf_context_t *ctx);

/* ComResponse field methods */

#define ngx_com_response__set_bid(obj, val) \
    NGX_PROTOBUF_SET_STRING(obj, bid, val)

#define ngx_com_response__clear_bid(obj) \
    NGX_PROTOBUF_CLEAR_STRING(obj, bid)

#define ngx_com_response__has_bid(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, bid))

#define ngx_com_response__set_adx_slot(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, adx_slot, val)

ngx_com_response_adx_slot_t *
ngx_com_response__add__adx_slot(
    ngx_com_response_t *obj,
    ngx_pool_t *pool);

#define ngx_com_response__clear_adx_slot(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, adx_slot)

#define ngx_com_response__has_adx_slot(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, adx_slot) && \
     (obj)->adx_slot->nelts > 0)

/* ComResponse message methods */

#define ngx_com_response__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_com_response_t))

#define ngx_com_response__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_com_response_t))

ngx_int_t ngx_com_response__is_initialized(
    ngx_com_response_t *obj);

ngx_int_t ngx_com_response__unpack(
    ngx_com_response_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_com_response__size(
    ngx_com_response_t *obj);

ngx_int_t ngx_com_response__pack(
    ngx_com_response_t *obj,
    ngx_protobuf_context_t *ctx);

#endif /* _NGX_ADX_COM_PROTO_H_INCLUDED_ */
